import { Project, Bid, Escrow, Transaction, EscrowState, ProjectCategory } from './types';

// --- Mock Projects ---
export const mockProjects: Project[] = [
  {
    id: 'proj-001',
    title: 'DeFi Dashboard Development',
    description: 'Build a comprehensive DeFi portfolio dashboard that aggregates positions across multiple protocols. Features include real-time price feeds, yield tracking, and historical P&L analysis. Must support Ethereum, Arbitrum, and Polygon networks.',
    category: ProjectCategory.WebDevelopment,
    budget: 2.5,
    milestones: [
      { id: 'ms-001-1', title: 'UI/UX Design & Architecture', description: 'Design system, component library, and app architecture', amount: 0.5, completed: true, approved: true },
      { id: 'ms-001-2', title: 'Core Dashboard & Price Feeds', description: 'Main dashboard with live price integration', amount: 1.0, completed: true, approved: false },
      { id: 'ms-001-3', title: 'Multi-chain & Analytics', description: 'Cross-chain support and portfolio analytics', amount: 1.0, completed: false, approved: false },
    ],
    clientAddress: '0x1234...abcd',
    freelancerAddress: '0x5678...ef01',
    status: 'in_progress',
    createdAt: '2026-02-15T10:00:00Z',
    deadline: '2026-04-15T10:00:00Z',
    bids: [],
    escrowId: 'esc-001',
  },
  {
    id: 'proj-002',
    title: 'NFT Marketplace Smart Contracts',
    description: 'Design and implement a suite of smart contracts for an NFT marketplace supporting ERC-721 and ERC-1155 tokens. Includes lazy minting, auction mechanism, royalty enforcement (EIP-2981), and an upgradeable proxy pattern.',
    category: ProjectCategory.SmartContracts,
    budget: 4.0,
    milestones: [
      { id: 'ms-002-1', title: 'Core Marketplace Contract', description: 'Listing, buying, and selling logic', amount: 1.5, completed: false, approved: false },
      { id: 'ms-002-2', title: 'Auction & Lazy Minting', description: 'English auction and gasless minting', amount: 1.5, completed: false, approved: false },
      { id: 'ms-002-3', title: 'Testing & Audit Prep', description: '100% test coverage and documentation', amount: 1.0, completed: false, approved: false },
    ],
    clientAddress: '0x1234...abcd',
    status: 'open',
    createdAt: '2026-03-01T14:30:00Z',
    deadline: '2026-05-01T14:30:00Z',
    bids: [
      { id: 'bid-002-1', projectId: 'proj-002', freelancerAddress: '0xaaaa...1111', amount: 3.8, timeline: 45, message: 'Experienced Solidity dev with 3 years of NFT marketplace development. Built contracts for OpenSea-style platforms.', createdAt: '2026-03-03T09:00:00Z', status: 'pending' },
      { id: 'bid-002-2', projectId: 'proj-002', freelancerAddress: '0xbbbb...2222', amount: 4.2, timeline: 30, message: 'Full-stack Web3 developer. Can deliver in 30 days with comprehensive testing. Previously audited by CertiK.', createdAt: '2026-03-04T16:00:00Z', status: 'pending' },
      { id: 'bid-002-3', projectId: 'proj-002', freelancerAddress: '0xcccc...3333', amount: 3.5, timeline: 60, message: 'Smart contract specialist. Will include gas optimization and proxy upgrade patterns.', createdAt: '2026-03-05T11:00:00Z', status: 'pending' },
    ],
  },
  {
    id: 'proj-003',
    title: 'DAO Governance Website',
    description: 'Create a modern, responsive website for a DAO governance platform. Includes proposal creation, voting interface, delegate management, and treasury overview. Integration with Snapshot and on-chain governance.',
    category: ProjectCategory.WebDevelopment,
    budget: 1.8,
    milestones: [
      { id: 'ms-003-1', title: 'Landing Page & Auth', description: 'Responsive landing page with wallet connect', amount: 0.6, completed: false, approved: false },
      { id: 'ms-003-2', title: 'Governance Interface', description: 'Voting, proposals, and delegate pages', amount: 0.8, completed: false, approved: false },
      { id: 'ms-003-3', title: 'Treasury & Analytics', description: 'Treasury dashboard and voting analytics', amount: 0.4, completed: false, approved: false },
    ],
    clientAddress: '0x9abc...def0',
    status: 'open',
    createdAt: '2026-03-10T08:00:00Z',
    deadline: '2026-04-25T08:00:00Z',
    bids: [
      { id: 'bid-003-1', projectId: 'proj-003', freelancerAddress: '0xdddd...4444', amount: 1.7, timeline: 35, message: 'React/Next.js expert with governance platform experience. Built UIs for MakerDAO and Compound.', createdAt: '2026-03-12T10:00:00Z', status: 'pending' },
    ],
  },
  {
    id: 'proj-004',
    title: 'Token Launch Landing Page',
    description: 'Design and develop a high-conversion landing page for an upcoming token launch. Includes tokenomics visualization, team section, roadmap timeline, countdown timer, and whitelist registration form.',
    category: ProjectCategory.Design,
    budget: 0.8,
    milestones: [
      { id: 'ms-004-1', title: 'Design & Development', description: 'Complete landing page with animations', amount: 0.5, completed: true, approved: true },
      { id: 'ms-004-2', title: 'Whitelist Integration', description: 'Registration form and email notifications', amount: 0.3, completed: true, approved: true },
    ],
    clientAddress: '0x9abc...def0',
    freelancerAddress: '0xeeee...5555',
    status: 'completed',
    createdAt: '2026-01-20T12:00:00Z',
    deadline: '2026-02-20T12:00:00Z',
    bids: [],
    escrowId: 'esc-002',
  },
  {
    id: 'proj-005',
    title: 'Cross-chain Bridge Protocol',
    description: 'Develop smart contracts for a cross-chain bridge supporting ETH, USDC, and USDT transfers between Ethereum and Arbitrum. Implement relayer logic, proof verification, and emergency pause mechanisms.',
    category: ProjectCategory.SmartContracts,
    budget: 8.0,
    milestones: [
      { id: 'ms-005-1', title: 'Bridge Architecture & Core Contracts', description: 'Lock/mint pattern implementation', amount: 3.0, completed: false, approved: false },
      { id: 'ms-005-2', title: 'Relayer & Proof Verification', description: 'Off-chain relayer and on-chain verification', amount: 3.0, completed: false, approved: false },
      { id: 'ms-005-3', title: 'Security & Emergency Controls', description: 'Pause, rate limiting, and audit prep', amount: 2.0, completed: false, approved: false },
    ],
    clientAddress: '0x5678...ef01',
    status: 'open',
    createdAt: '2026-03-15T09:00:00Z',
    deadline: '2026-06-15T09:00:00Z',
    bids: [],
  },
  {
    id: 'proj-006',
    title: 'Web3 Analytics Dashboard',
    description: 'Build a data analytics platform for tracking on-chain metrics including TVL, active addresses, transaction volumes, and gas usage across L2 networks. Real-time charts and exportable reports.',
    category: ProjectCategory.DataScience,
    budget: 3.2,
    milestones: [
      { id: 'ms-006-1', title: 'Data Pipeline Setup', description: 'Indexer and data aggregation pipeline', amount: 1.2, completed: false, approved: false },
      { id: 'ms-006-2', title: 'Dashboard UI', description: 'Interactive charts and filtering', amount: 1.2, completed: false, approved: false },
      { id: 'ms-006-3', title: 'Reports & Export', description: 'PDF/CSV export and scheduled reports', amount: 0.8, completed: false, approved: false },
    ],
    clientAddress: '0x1234...abcd',
    status: 'open',
    createdAt: '2026-03-12T14:00:00Z',
    deadline: '2026-05-12T14:00:00Z',
    bids: [
      { id: 'bid-006-1', projectId: 'proj-006', freelancerAddress: '0xffff...6666', amount: 3.0, timeline: 50, message: 'Data engineer with experience building Dune-like dashboards. Proficient in The Graph and custom indexers.', createdAt: '2026-03-14T09:00:00Z', status: 'pending' },
      { id: 'bid-006-2', projectId: 'proj-006', freelancerAddress: '0x1111...7777', amount: 3.4, timeline: 40, message: 'Full-stack dev specializing in data visualization. Built analytics tools for major DeFi protocols.', createdAt: '2026-03-15T15:00:00Z', status: 'pending' },
    ],
  },
];

// --- Mock Escrows ---
export const mockEscrows: Escrow[] = [
  {
    id: 'esc-001',
    projectId: 'proj-001',
    projectTitle: 'DeFi Dashboard Development',
    clientAddress: '0x1234...abcd',
    freelancerAddress: '0x5678...ef01',
    totalAmount: 2.5,
    state: EscrowState.InProgress,
    milestones: mockProjects[0].milestones,
    contractAddress: '0x7890...cdef',
    createdAt: '2026-02-18T12:00:00Z',
    fundedAt: '2026-02-18T12:30:00Z',
  },
  {
    id: 'esc-002',
    projectId: 'proj-004',
    projectTitle: 'Token Launch Landing Page',
    clientAddress: '0x9abc...def0',
    freelancerAddress: '0xeeee...5555',
    totalAmount: 0.8,
    state: EscrowState.Completed,
    milestones: mockProjects[3].milestones,
    contractAddress: '0xabcd...1234',
    createdAt: '2026-01-25T10:00:00Z',
    fundedAt: '2026-01-25T10:15:00Z',
    completedAt: '2026-02-18T16:00:00Z',
  },
];

// --- Mock Transactions ---
export const mockTransactions: Transaction[] = [
  {
    id: 'tx-001',
    type: 'EscrowDeployed',
    projectId: 'proj-001',
    projectTitle: 'DeFi Dashboard Development',
    fromAddress: '0x1234...abcd',
    txHash: '0xabc123...def456',
    blockNumber: 18234567,
    timestamp: '2026-02-18T12:00:00Z',
    details: 'Escrow contract deployed for DeFi Dashboard Development',
  },
  {
    id: 'tx-002',
    type: 'EscrowFunded',
    projectId: 'proj-001',
    projectTitle: 'DeFi Dashboard Development',
    fromAddress: '0x1234...abcd',
    amount: 2.5,
    txHash: '0xdef789...abc012',
    blockNumber: 18234590,
    timestamp: '2026-02-18T12:30:00Z',
    details: 'Client funded escrow with 2.5 ETH',
  },
  {
    id: 'tx-003',
    type: 'MilestoneApproved',
    projectId: 'proj-001',
    projectTitle: 'DeFi Dashboard Development',
    fromAddress: '0x1234...abcd',
    toAddress: '0x5678...ef01',
    amount: 0.5,
    txHash: '0x111222...333444',
    blockNumber: 18245678,
    timestamp: '2026-03-01T15:00:00Z',
    details: 'Milestone "UI/UX Design & Architecture" approved and 0.5 ETH released',
  },
  {
    id: 'tx-004',
    type: 'ProjectCreated',
    projectId: 'proj-002',
    projectTitle: 'NFT Marketplace Smart Contracts',
    fromAddress: '0x1234...abcd',
    txHash: '0x555666...777888',
    blockNumber: 18256789,
    timestamp: '2026-03-01T14:30:00Z',
    details: 'New project posted: NFT Marketplace Smart Contracts (4.0 ETH budget)',
  },
  {
    id: 'tx-005',
    type: 'EscrowDeployed',
    projectId: 'proj-004',
    projectTitle: 'Token Launch Landing Page',
    fromAddress: '0x9abc...def0',
    txHash: '0x999aaa...bbbccc',
    blockNumber: 18200000,
    timestamp: '2026-01-25T10:00:00Z',
    details: 'Escrow contract deployed for Token Launch Landing Page',
  },
  {
    id: 'tx-006',
    type: 'PaymentReleased',
    projectId: 'proj-004',
    projectTitle: 'Token Launch Landing Page',
    fromAddress: '0x9abc...def0',
    toAddress: '0xeeee...5555',
    amount: 0.8,
    txHash: '0xddd111...222eee',
    blockNumber: 18220000,
    timestamp: '2026-02-18T16:00:00Z',
    details: 'Full payment of 0.8 ETH released to freelancer',
  },
  {
    id: 'tx-007',
    type: 'ProjectCreated',
    projectId: 'proj-003',
    projectTitle: 'DAO Governance Website',
    fromAddress: '0x9abc...def0',
    txHash: '0xfff333...444ggg',
    blockNumber: 18260000,
    timestamp: '2026-03-10T08:00:00Z',
    details: 'New project posted: DAO Governance Website (1.8 ETH budget)',
  },
  {
    id: 'tx-008',
    type: 'ProjectCreated',
    projectId: 'proj-005',
    projectTitle: 'Cross-chain Bridge Protocol',
    fromAddress: '0x5678...ef01',
    txHash: '0xhhh555...666iii',
    blockNumber: 18270000,
    timestamp: '2026-03-15T09:00:00Z',
    details: 'New project posted: Cross-chain Bridge Protocol (8.0 ETH budget)',
  },
];
